frr version 10
frr defaults traditional
hostname r3
service integrated-vtysh-config
log syslog informational

!

interface eth1
 ip address 10.255.23.2/30

interface eth2
 ip address 10.10.30.1/24

!

router ospf
 ospf router-id 3.3.3.3

 network 10.255.23.0/30 area 0
 network 10.10.30.0/24 area 0

!

line vty