---
- name: Install apache web server
  hosts: web1
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
    
    - name: Install Apache2
      apt:
        name: apache2
        state: present

    - name: Start and enable Apache2 service
      ansible.builtin.sysvinit:
        name: apache2
        state: started
        enabled: yes

    - name: Print hostname to index.html
      copy:
        dest: /var/www/html/index.html
        content: "<h1> {{ inventory_hostname }} </h1>"
  