frr version 10
frr defaults traditional
hostname r2
service integrated-vtysh-config
log syslog informational

!
! Linkki r1:lle
!
interface eth1
 ip address 10.255.12.2/30

!
! Serveriverkko
!
interface eth2
 ip address 10.10.20.1/24

!
! Hallintaverkko
!
interface eth3
 ip address 10.10.99.1/24

!
! Linkki r3:lle
!
interface eth4
 ip address 10.255.23.1/30

!
router ospf
 ospf router-id 2.2.2.2

 network 10.255.12.0/30 area 0
 network 10.255.23.0/30 area 0
 network 10.10.20.0/24 area 0
 network 10.10.99.0/24 area 0

!
line vty